# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-14 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RowData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seat_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScreenData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('row_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeatData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('aisle_seat', models.BooleanField(default=False)),
                ('is_reserved', models.BooleanField(default=False)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.RowData')),
            ],
        ),
        migrations.AddField(
            model_name='rowdata',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.ScreenData'),
        ),
        migrations.AddField(
            model_name='reservationdata',
            name='seat_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.SeatData'),
        ),
    ]
