# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-14 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatdata',
            old_name='is_reserved',
            new_name='reserved',
        ),
    ]
