# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-14 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_auto_20181014_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screendata',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
